{block content}
{include "../Checkout/find-user.phtml"}
<!-- START CLIENT AND SERVICE DETAILS -->
	<div class="userWrapper">
        	
   	  <div class="searchBoxUser">
        {widget searchForm begin}
        	{$control['searchForm']['q']->control}            	
            <div class="searchBtnUser"><a href="#" onclick="$('form').submit();" title="Search"><div class="searchIconUser"><img src="{$basePath}/images/icon-search-med.png" width="40" height="42" alt="Search" /></div></a></div>
            <div class="clear"></div>
        {widget searchForm end}
        </div>
        <div class="userResultWrapper qs-results" style="display:none;">
	    	<div class="resultBoxUser">
	            <div id="snippet--results" ></div>            
	 		</div>
			<div class="addClientBtnUser clear"><a href="{link Profile:adduser}" title="Add Client"></a></div>
		</div>	
        <div class="checkoutBtnUser floatRight"><a href="#" onclick="sms.checkout.show_checkout_step_1(); return false;" title="Checkout"></a></div>
        <div class="clear"></div>
        </div>
	
    	<div class="userWrapper">

        	<div class="popupBox">
            	{if $searching }
                <div class="popupHdrBar">                	
                    <h4>Search Results: User</h4>
                </div>
                
                <div class="clientName">
                {$search}                
                </div>
            	<div class="notes"><p>{$num_results} results</p></div>
            	<script type="text/javascript">

        $('.searchBoxUser input').attr({'autocomplete':'off'})
        	.focus()
        	.bind('keydown', { url: {link QuickSearch:quicksearchuser}}, sms.quicksearch.keydown)	
        	.bind('keyup', { url: {link QuickSearch:quicksearchuser}}, sms.quicksearch.keyup);

        sms.quicksearch.url = {link QuickSearch:quicksearchuser};

        </script>
				{/if}
                
                <div class="transactionsBox">
						<ul class="purpleBar">
                        	<li>
                            <span class="clName"><p><a href={link Profile:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('name')}>Client Name{if $order_column == 'name'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('name') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="stylistName"><p>Phone Number(s)</p></span>
                            <span class="transaction"><p><a href={link Profile:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('last_transaction_date')}>Last Transaction{if $order_column == 'last_transaction_date'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('last_transaction_date') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="editBtns"><p></p></span>

                            </li>
                        </ul>
                        {foreach $users as $user}						
                        <ul class="row{if ($iterator->isOdd())}White{else}Grey{/if}">
                            <li>
                                <a href="{link Profile:edit 'id'=>$user->uid}">
                                <span class="clName">{$user->name}</span>
                                <span class="stylistName">{if empty($user->phone_number)}--{else}{$user->phone_number}{/if}</span>
                                <span class="transaction">{$presenter->formatDate($user->last_transaction_date)}</span>

                                </a>
                                <div onclick='location.href={link Profile:edit id=>$user->uid}' class="editBtns">
                                	
                                    <table cellpadding="0" cellspacing="0" class="yellowBtnHolder floatRight">
                                        <tr>
                                            <td class="yellowBtnLeft"></td>
                                            <td class="yellowBtnMid"><p>Edit&nbsp;Profile</p></td>
                                            <td class="yellowBtnRight"></td>
                                        </tr>

                                     </table>
                                    </a>
                                </div>
                             </li>
                	    </ul>
                    	{/foreach}
                    	{if $num_results > $page_size}
                    	<div class="paginationBar">

                        	<table cellpadding="0" cellspacing="0">
                            	<tr>
                                	<td width="130">
                                		<div class="prevPage">
                                			<a href="{link Profile:search 'search' => $search,'page' => $page_prev, 'order' => $order}" title="Previous Page">
                                				<img src="{$basePath}/images/left-white-arrow.png" alt="Previous Page">&nbsp; Previous Page</a>
                                		</div>
                                	</td>
                                    <td width="780"  class="pagination">
                                    {if $page == 0}1{else}<a href="{link Profile:search 'search' => $search, 'page' => 0, 'order' => $order}">1</a>{/if}
                                    {if $page > 6}...{/if}
                                    {for $i=($page - 6 < 0 ? 1 : $page - 6); $i < ($page + 6 > $max_page - 1 ? $max_page - 1 : $page + 6); $i++} 
                                    {if $i == $page}{$i + 1}{else}<a href="{link Profile:search 'search' => $search, 'page' => $i, 'order' => $order}">{$i+1}</a>{/if}
                                    {/for} 
                                    {if $page < $max_page - 7}...{/if}                                  
                                    {if $page == $max_page - 1}{$max_page}{else}<a href="{link Profile:search 'search' => $search, 'page' => $max_page - 1, 'order' => $order}">{$max_page}</a>{/if}
                                    </td>
                                    <td width="130"><div class="nextPage"><a href="{link Profile:search 'search' => $search,'page' => $page_next, 'order' => $order}" title="Next Page">Next Page &nbsp;<img src="{$basePath}/images/right-white-arrow.png" alt="Next Page"></a></div></td>
                                </tr>
                            </table>
                        </div>

                    	{/if}
       		  		</div>
            	</div>	
            <div class="clear"></div>

		</div>
<!-- END CLIENT AND SERVICE DETAILS -->
{/block}