<div class="popupBox apptPopup" id="dialog-appointment-add" style="display:none;">
        	<div class="titleBar clearfix" style="cursor:move;">
        	<div class="closeBtn floatRight"><p><a href="#" title="Close Window"><span class="closeIcon"></span>Close</a></p></div>
            <div class="floatLeft"><p><span class="moveIcon"></span>Add Appointment</p></div>
            </div>
       {widget addForm begin}
	   <div style="display:none;" class="fUID"> {$control['addForm']['client_uid']->control}</div>
    <div class="subTitleBar apptClient"><p>Client - <a href="#" class="client_link" target="_blank">View Profile</a></p></div>
          <div class="apptClientInput fClientName">{$control['addForm']['client_name']->control}</div>
			 <div class="resultBox qs-results" style="display:none;">
            <div class="snippet--appointmentresults"></div>
            </div>

            <div class="subTitleBar apptClient"><p>E-Mail Address</p></div>
            <div class="apptClientInput inputSmall fEmailAddress">
				{$control['addForm']['email_address']->control}
			</div>

		   <div class="subTitleBar apptClient"><p>Phone Number</p></div>
            <div class="apptClientInput inputSmall fPhoneNumber">
				{$control['addForm']['phone_number']->control}
			</div>

 <div class="subTitleBar apptClient"><p>Service</p></div>
            <div class="fService">
              {$control['addForm']['service']->control}
          </div>

            <div class="subTitleBar apptClient"><p>Stylist</p></div>
            <div class="fStylist">
               {$control['addForm']['stylist']->control}
          </div>

            <div class="fDate" style="display:none;">{$control['addForm']['date']->control}</div>

<table cellpadding="0" cellspacing="0">
            	<tr>
                	<td><div class="startTime subTitleBar "><p>Start Time</p></div></td>
                    <td><div class="endTime subTitleBar"><p>End Time</p></div></td>
                </tr>
                <tr>
                	<td><div class="startTimeInput inputSmall fStartTime">{$control['addForm']['startTime']->control}</div></td>
                    <td><div class="endTimeInput inputSmall fEndTime">{$control['addForm']['endTime']->control}</div></td>
                </tr>
            </table>

            <div class="clear"></div>

            <div class="apptSaveDeleteBox clearfix">
            	<div class="actionBtn floatLeft fSave"><h4><a href="#" title="Book This Appoinment">Book It!</a></h4></div>
                <div class="cancelActionBox floatLeft">
                  <h4>or <a href="#" class="redLink fDelete" title="Cancel This Appoinment">Cancel</a></h4></div>
            </div>

            <div class="tenPxSpacer"></div>
        {widget addForm end}

        </div>

<div class="popupBox apptPopup" id="dialog-appointment-edit" style="display:none;">
        	<div class="titleBar clearfix" style="cursor:move;">
        	<div class="closeBtn floatRight"><p><a href="#" title="Close Window"><span class="closeIcon"></span>Close</a></p></div>
            <div class="floatLeft"><p><span class="moveIcon"></span>Edit Appointment</p></div>
            </div>
       {widget editForm begin}
       <div style="display:none;" class="fID"> {$control['editForm']['appointment_id']->control}</div>
	   <div style="display:none;" class="fUID"> {$control['editForm']['client_uid']->control}</div>
    <div class="subTitleBar apptClient"><p>Client - <a href="#" class="client_link" target="_blank">View Profile</a></p></div>
          <div class="apptClientInput fClientName">{$control['editForm']['client_name']->control}</div>
		   <div class="resultBox qs-results" style="display:none;">
            <div class="snippet--appointmentresults"></div>
            </div>

            <div class="subTitleBar apptClient"><p>E-Mail Address</p></div>
            <div class="apptClientInput inputSmall fEmailAddress">
				{$control['addForm']['email_address']->control}
			</div>
 <div class="subTitleBar apptClient"><p>Phone Number</p></div>
            <div class="apptClientInput inputSmall fPhoneNumber">
				{$control['addForm']['phone_number']->control}
			</div>

 <div class="subTitleBar apptClient"><p>Service</p></div>
            <div class="fService">
              {$control['editForm']['service']->control}
          </div>

            <div class="subTitleBar apptClient"><p>Stylist</p></div>
            <div class="fStylist">
               {$control['editForm']['stylist']->control}
          </div>

            <div class="fDate" style="display:none;">{$control['editForm']['date']->control}</div>

<table cellpadding="0" cellspacing="0">
            	<tr>
                	<td><div class="startTime subTitleBar "><p>Start Time</p></div></td>
                    <td><div class="endTime subTitleBar"><p>End Time</p></div></td>
                </tr>
                <tr>
                	<td><div class="startTimeInput inputSmall fStartTime">{$control['editForm']['startTime']->control}</div></td>
                    <td><div class="endTimeInput inputSmall fEndTime">{$control['editForm']['endTime']->control}</div></td>
                </tr>
            </table>

            <div class="clear"></div>

            <div class="apptSaveDeleteBox clearfix">
            	<div class="actionBtn floatLeft fSave"><h4><a href="#" title="Book This Appoinment">Save!</a></h4></div>
                <div class="cancelActionBox floatLeft">
                  <h4>or <a href="#" class="redLink fDelete" title="Delete This Appoinment">Delete</a></h4></div>
            </div>

            <div class="tenPxSpacer"></div>

            <div class="subTitleBar" style="text-align:center;">
            	<p><a class="checkoutAppointmentLink" href="#" title="Checkout This Person"><span class="smallCalIcon"></span> Checkout This Person</a></p>
            </div>
        {widget editForm end}

        </div>

