@{block content}
<div class="popupBG">
        	<div class="popupBorder">
       		<div class="popupBox">
            	
                <div class="popupPurpleBar">
                	<div class="closeBtnPurple"><a href="{if $transaction_type == 'new'}{link Default:}{else}{link Checkout:cancelTransaction 'transaction_id' => $transaction_id}{/if}" onclick="return confirm('Do you really want to {if $transaction_type == 'finalized'}{if $transaction_void}unvoid{else}void{/if}{else}cancel{/if} this transaction?');">
                	{if $transaction_type == 'finalized'}{if $transaction_void}Unvoid{else}Void{/if} Transaction{else}Cancel Transaction{/if}
                	</a></div>
                    <h4>CONFIRM TRANSACTION</h4>
                </div>
                
                <div class="clientName"><A HREF="{link Profile:edit 'id' => $transaction_uid}">{$client_name}</a></div>
                <div class="notes"><p>Confirm the Services and/or Products purchased by this Client.</p></div>
                
                 {if count($services) > 0}
            	<div class="transactionsBox">
                        	<div class="darkGreyBar">
                            	<p>Services Received</p>
                                <div class="clear"></div>

                            </div>
                           
                            {foreach $services as $service}
                            <div class="itemRow">
                            	<div class="confirmTrans">
                            		<div class="ltGreyBar"><p>Service</p></div>
                                	<div class="checkedInClients"> 
                            			<div class="pricepoint">{$service->service_name}</div>
                          			</div>
                            	</div>

                            
                            	<div class="confirmTrans">
                            		<div class="ltGreyBar"><p>Stylist</p></div>
                                	<div class="checkedInClients"> 
                            			<div class="pricepoint">{$service->stylist_name}</div>
                          			</div>
                            	</div>
                            
                            	<div class="pricetag">
                            		<div class="ltGreyBar"><h5>Price</h5></div>

                                	<div class="pricepoint">${$service->price}</div>
                            	</div>
                            
                            	<div class="clear"></div>
                            </div>
                            {/foreach}
                            <div>
                            	<div class="subtotalTxtConfirm">Services Subtotal:</div>
                                <div class="subtotalNum">${$services_subtotal}</div>

                                <div class="clear"></div>
                            </div>
                            
                        </div>
                        {/if}
                        {if count($products) > 0}
                        <div class="transactionsBox">
                        	<div class="darkGreyBar">
                            	<p>Products Purchased</p>
                                <div class="clear"></div>
                            </div>

                            {foreach $products as $product}
                            <div class="itemRow">
                            	<div class="confirmTrans" style="width:374px;">
                            		<div class="ltGreyBar"><p>Product Name</p></div>
                                	<div class="checkedInClients"> 
                            			<div class="checkedInClients"> 
                            			<div class="pricepoint">{$product->product_name}</div>
                          			</div>
                          			</div>                                    
                            	</div>
                            	 <div class="confirmTrans qty">
                            		<div class="ltGreyBar"><h5>QTY</h5></div>
                                	<div class="checkedInClients"> 
                            			<div class="pricepoint" style="text-align:center;">{$product->quantity}</div>
                          			</div>
                            	</div>
                            	
                            	<div class="confirmTrans">
                            		<div class="ltGreyBar"><p>Product sold by</p></div>
                                	<div class="checkedInClients"> 
                            			<div class="checkedInClients"> 
                            			<div class="pricepoint">{$product->user_name}</div>

                          			</div>
                          			</div>                                    
                            	</div>                            
                            	<div class="pricetag">
                            		<div class="ltGreyBar"><h5>Price</h5></div>
                                	<div class="pricepoint">${$product->price}</div>                                    
                            	</div>
                            
                            	<div class="clear"></div>

                            </div>
                            {/foreach}
                            <div>
                            	<div class="subtotalTxtConfirm">Products Subtotal:</div>
                                <div class="subtotalNum">${$products_subtotal}</div>
                                <div class="clear"></div>
                            </div>
                            
                        </div>
                        {/if}
                        <div class="transactionsBox">

                        	<div class="darkGreyBar">
                            	<p>The Bottom Line</p>
                                <div class="clear"></div>
                            </div>
                            
                            <div class="itemRow">
                            	<div class="category">
                            		<div class="ltGreyBar"><p>Promotional Code?</p></div>
                                	<div class="checkedInClients"> 
                            			<div class="pricepoint">Unavailable</div>

                          			</div>
                            	</div>
                            	
                            	<div class="finalPrice">
                            		<div class="ltGreyBar"><h5>Payment Method</h5></div>
                                	<div class="checkedInClients"> 
                            			{$payment_type}
                          			</div>
                            	</div>
                            
                            	<div class="finalPrice">
                            		<div class="ltGreyBar"><p>Subtotal</p></div>
                                	<div class="checkedInClients"> 
                            			<div class="pricepoint">${$subtotal}</div>
                          			</div>
                            	</div>

                            
                            	<div class="pricetag">
                            		<div class="ltGreyBar"><h5>Taxes</h5></div>
                                	<div class="pricepoint">${$taxes}</div>
                            	</div>
                            
                            	<div class="grandTotal">
                            		<div class="purpleBarCheckout"><h5>GRAND TOTAL</h5><h4>${$grand_total}</h4></div>
                            	</div>

                            
                            	<div class="clear"></div>
                            </div>
                            
                            <div class="ConfirmTransaction floatLeft"><a href="{link Checkout:confirm 'transaction_id' => $transaction_id}" title="Confirm Transaction"></a></div>
                        	<div class="GoBackMakeChanges floatLeft"><a href="{link Checkout:order 'transaction_id' => $transaction_id}" title="Go Back and Make Changes"></a></div>
                            <div class="clear"></div>
                            
                        </div>
            	
        		</div>
            </div>
        </div>

{/block}