@{block content}
{include "../Checkout/find-user.phtml"}
 <!-- START TOP SEARCH AND CHECKOUT -->
    	<div class="userWrapper">
    	<div class="userResultWrapper qs-results" style="display:none;">
    	<div class="resultBoxUser">
            <div id="snippet--results" ></div>

		 </div>
		 <div class="addClientBtnUser clear"><a href="{link Profile:adduser}" title="Add Client"></a></div>
		 </div>
    	<div class="searchBoxUser">
         {widget searchForm begin}
		            	{$control['searchForm']['q']->control}
		                <div class="searchBtnUser"><a href="#" onclick="$('form').submit();" title="Search"><div class="searchIconUser"><img src="{$basePath}/images/icon-search-med.png" width="40" height="42" alt="Search" /></div></a></div>
		                <div class="clear"></div>
		 {widget searchForm end}
		 </div>

   	  	 <div class="checkoutBtnUser floatRight"><a href="#" onclick="sms.checkout.show_checkout_step_1(); return false;" title="Checkout"></a></div>

         <div class="clear"></div>

        </div>

        <script type="text/javascript">

        $('.searchBoxUser input').attr({'autocomplete':'off'})
        	.focus()
        	.focusout(sms.quicksearch.hide)
        	.bind('keydown', { url: {link QuickSearch:quicksearchuser}}, sms.quicksearch.keydown)
			.bind('keyup', { url: {link QuickSearch:quicksearchuser}}, sms.quicksearch.keyup);

        sms.quicksearch.url = {link QuickSearch:quicksearchuser};

        </script>
    <!-- END TOP SEARCH AND CHECKOUT -->

    <!-- START CLIENT AND SERVICE DETAILS -->
    	<div class="userWrapper">

        	<div class="popupBox">

            	{if empty($uid)}
                <div class="popupHdrBar">
                    <h4>Search Results: Transactions</h4>
                </div>

                <div class="clientName">{if !empty($search)}#{$search}{/if}</div>
                {/if}
                {if !empty($uid)}
                <div class="popupHdrBar">
                    <h4>Transactions Of A Client</h4>
                </div>

                <div class="clientName"><a href={link Profile:edit 'id'=>$uid}>{$client_name}</a></div>
                {/if}
            	<div class="notes"><p>{$total_results} results</p></div>


                <div class="transactionsBox">
						<ul class="purpleBar">
                        	<li>
                        	<span class="idNum"><p><a href={link Checkout:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('transaction_code')}>ID#{if $order_column == 'transaction_code'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('transaction_code') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="idNum"><p><a href={link Checkout:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('transaction_created_date')}>Date{if $order_column == 'transaction_created_date'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('transaction_created_date') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="clName"><p><a href="#" title="Sort"><a href={link Checkout:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('transaction_client_name')}>Client Name{if $order_column == 'transaction_client_name'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('transaction_client_name') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="stylistName"><p><a href={link Checkout:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('transaction_stylists')}>Stylist(s){if $order_column == 'transaction_stylists'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('transaction_stylists') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="stylistName"><p><a href={link Checkout:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('transaction_products')}>Products Purchased{if $order_column == 'transaction_products'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('transaction_products') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="noteIcon"></span>
                            <span class="total"><p><a href={link Checkout:search 'search' => $search, 'page' => 0, 'order' => $presenter->createOrderString('transaction_total')}>Total{if $order_column == 'transaction_total'}&nbsp;<img src="{$basePath}/images/{if $presenter->getOrderDir('transaction_total') == 'DESC'}down{else}up{/if}-white-arrow.png" width="7" height="4" alt="Sort Down">{/if}</a></p></span>
                            <span class="editBtns"><p></p></span>
                            </li>
                        </ul>
                        {foreach $results as $t}
                        <ul id="trans-{$t->transaction_id}" class="row{if $iterator->isOdd()}White{else}Grey{/if}">
                            <li>
                                <a href="{link Checkout:order 'transaction_id' => $t->transaction_id}">
                                <span class="idNum {if $t->transaction_void == 1}void{/if}">{$t->transaction_code}</span>
                                <span class="idNum {if $t->transaction_void == 1}void{/if}">{$presenter->formatDate($t->transaction_created_date)}</span>
                                <span class="clName {if $t->transaction_void == 1}void{/if}">{$t->transaction_client_name}</span>
                                <span class="stylistName {if $t->transaction_void == 1}void{/if}">{$t->transaction_stylists}</span>
                                <span class="stylistName {if $t->transaction_void == 1}void{/if}">{$t->transaction_products}</span>
								<span class="total {if $t->transaction_void == 1}void{/if}">${$presenter->formatPrice($t->transaction_total)}</span>
                                </a>
                                <div class="editBtns">
                                    <table cellpadding="0" cellspacing="0" class="yellowBtnHolder floatLeft" onClick="window.location.href='#'">
                                        <tr>
                                            <td class="yellowBtnLeft"></td>
                                            <td class="yellowBtnMid" onclick='location.href={link Checkout:order 'transaction_id' => $t->transaction_id}'><p>Edit&nbsp;Details</p></td>

                                            <td class="yellowBtnRight"></td>
                                        </tr>
                                     </table>
                                    <div class="deleteBtn{if $t->transaction_void == 1}Void{/if} floatLeft"><a href="#" onclick="if (confirm('Do you really want to change this transaction?')) { sms.order.voidTrans({$t->transaction_id}); return false; }" title=" {if $t->transaction_void == 1}Unvoid{else}Void{/if}This"></a></div>
                                </div>
                             </li>
                	    </ul>
                        {/foreach}
                   		{if $num_results > $page_size}
                    	<div class="paginationBar">

                        	<table cellpadding="0" cellspacing="0">
                            	<tr>
                                	<td width="130">
                                		<div class="prevPage">
                                			<a href="{link Checkout:search 'search' => $search, 'order' => $order,'page' => $page_prev, 'uid' => $uid}" title="Previous Page">
                                				<img src="{$basePath}/images/left-white-arrow.png" alt="Previous Page">&nbsp; Previous Page</a>
                                		</div>
                                	</td>
                                    <td width="780"  class="pagination">
                                    {if $page == 0}1{else}<a href="{link Checkout:search 'search' => $search, 'order' => $order, 'page' => 0, 'uid' => $uid}">1</a>{/if}
                                    {if $page > 6}...{/if}
                                    {for $i=($page - 6 < 0 ? 1 : $page - 6); $i < ($page + 6 > $max_page - 1 ? $max_page - 1 : $page + 6); $i++}
                                    {if $i == $page}{$i + 1}{else}<a href="{link Checkout:search 'search' => $search, 'order' => $order, 'page' => $i, 'uid' => $uid}">{$i+1}</a>{/if}
                                    {/for}
                                    {if $page < $max_page - 7}...{/if}
                                    {if $page == $max_page - 1}{$max_page}{else}<a href="{link Checkout:search 'search' => $search, 'order' => $order, 'page' => $max_page - 1, 'uid' => $uid}">{$max_page}</a>{/if}
                                    </td>
                                    <td width="130"><div class="nextPage"><a href="{link Checkout:search 'search' => $search, 'order' => $order,'page' => $page_next, 'uid' => $uid}" title="Next Page">Next Page &nbsp;<img src="{$basePath}/images/right-white-arrow.png" alt="Next Page"></a></div></td>
                                </tr>
                            </table>
                        </div>

                    	{/if}
       		  		</div>
            	</div>
            <div class="clear"></div>
			<script type="text/javascript">
			sms.order.transURL = {link Checkout:void}
			</script>
		</div>
<!-- END CLIENT AND SERVICE DETAILS -->

{/block}