<div style="margin-bottom:10px; margin-left:auto; margin-right:auto; width:400px;">
	<div style="float:left;" class="adminBtn"><a href="{link Reports:daily}" title="View Daily Summary">Daily Summary</a></div>
	<div style="float:left;" class="adminBtn"><a href="{link Reports:retail}" title="View Retail Report">Retail</a></div>
	<div style="float:left;" class="adminBtn"><a href="{link Reports:payrolls}" title="View Payroll">Payroll</a></div>
	<div style="float:left;" class="adminBtn"><a href="{link Reports:merchant}" title="View Merchant">Merchant</a></div>
	<div class="clear"></div>
</div>