@{block content}
{include "../Checkout/find-user.phtml"}
 <!-- START TOP SEARCH AND CHECKOUT -->
    	<div class="userWrapper">
    	<div class="userResultWrapper qs-results" style="display:none;">
    	<div class="resultBoxUser">
            <div id="snippet--results" ></div>
            
		 </div>
		 <div class="addClientBtnUser clear"><a href="{link Profile:adduser}" title="Add Client"></a></div>
		 </div>	 
    	<div class="searchBoxUser">
         {widget searchForm begin}
		            	{$control['searchForm']['q']->control}            	
		                <div class="searchBtnUser"><a href="#" onclick="$('form').submit();" title="Search"><div class="searchIconUser"><img src="{$basePath}/images/icon-search-med.png" width="40" height="42" alt="Search" /></div></a></div>
		                <div class="clear"></div>
		 {widget searchForm end} 
		 </div>		 
		 
   	  	 <div class="checkoutBtnUser floatRight"><a href="#" onclick="sms.checkout.show_checkout_step_1(); return false;" title="Checkout"></a></div>
         
         <div class="clear"></div>	
		 
        </div>
        
        <script type="text/javascript">

        $('.searchBoxUser input').attr({'autocomplete':'off'})
        	.focus()
        	.bind('keydown', { url: {link QuickSearch:quicksearchuser}}, sms.quicksearch.keydown)	
			.bind('keyup', { url: {link QuickSearch:quicksearchuser}}, sms.quicksearch.keyup);

        sms.quicksearch.url = {link QuickSearch:quicksearchuser};

        </script>
    <!-- END TOP SEARCH AND CHECKOUT -->
    
    <!-- START CLIENT AND SERVICE DETAILS -->
    	<div class="userWrapper">

        	<div class="popupBox">
            	
            	{include 'navigation.phtml'}
            	
                <div class="popupHdrBar">                	
                    <h4>Retail report</h4>
                </div>
                                
                <div class="transactionsBox">					                    
                    {widget retailFilterForm begin}
                    
<!--
RETAIL REPORT
Date Range: Weekly
Input: $start_date Select a date within the week you want to view

Outputs:
-Total Product Revenue
-Revenue by Brand (currently uses MySQL SUBSTR() to get brand name)
  -# of products sold per brand
  -$$ of products sold per brand
  -Sums the total which gives # of products sold total and $$$ sold.

-Revenue by Product - 
  -# of products sold per product
  -$$ of products sold per product
  -Sums the total
-->
                    <table>
                    <tr>
                    	<th align="left">Date</th>
                    	<td id="datepicker" style="width:650px;">{$control['filterForm']['date']->control} use dd/mm/YYYY notation</td>
                    </tr>
                    
                    <tr>
                    	<td colspan="2">
                    	<br/>
                    		{$control['filterForm']['show']->control}
                    	</td>
                    </tr>
                    
                    </table>
                    
                    	
                    {widget retailFilterForm end}
                    
                    {if $show_report}
                    
                    <br/><br/>
                    
                    <!-- TOTAL REVENUE -->
                    <table cellpadding="0" cellspacing="0" style="margin-bottom:20px; border-collapse:collapse; width:500px;">
                    	
                    	<tr>
                    		<th>Total <strong>retail sold</strong> for week of:  <strong>{$presenter->formatDate($start_date, 'n/j/Y')} - {$presenter->formatDate($end_date, 'n/j/Y')}</strong></th>
                    		<th colspan="2" align="right">${$presenter->formatPrice($total_revenue)}</th>
                    	</tr>
                    	
                    	<tr style="height:40px;"><td colspan="3">&nbsp;</td></tr>
                    
                    <!-- Retail REVENUE -->
                                        	
                    	<tr style="border-bottom:1px black solid;">
                    		<th>Company</th>
                    		<th>#</th>
                    		<th>Amount</th>
                    	</tr>
                    	{foreach $results['entries'] as $entry}
                    	<tr>
                    		<td>{$entry['name']}</td>
                    		<td align="right">{$entry['count']}</td>
                    		<td align="right">${$presenter->formatPrice($entry['sum'])}</td>
                    	</tr>
                    	{/foreach}
                    	<tr style="border-top:1px black solid;">
                    		<th>Retail subtotal</th>
                    		<td>{$results['totalcount']}</td>
                    		<th align="right">${$presenter->formatPrice($results['total'])}</th>
                    	</tr>
						<tr><td>&nbsp;</td></tr>
		             <!-- TAXES -->

	                    <tr style="border-bottom:1px black solid;">
                    		<th>Tax</th>
                    		<th></th>
                    		<th>Amount</th>
                    	</tr>                    	
                    	<tr style="border-top:1px black solid;">
                    		<th>Tax total</th>
                    		<td></td>
                    		<th align="right">${$presenter->formatPrice($total_tax)}</th>
                    	</tr>

	<tr style="height:40px;">&nbsp;</tr>
	
						 <!-- Individual Product Sales -->

		                    <tr style="border-bottom:1px black solid;">
	                    		<th>Product Name</th>
	                    		<th>#</th>
	                    		<th>Amount</th>
	                    	</tr>           
	         				{foreach $individual_results['entries'] as $entry}
	                    	<tr>
	                    		<td>{$entry['name']}</td>
	                    		<td>{$entry['count']}</td>
	                    		<td align="right">${$presenter->formatPrice($entry['amount'])}</td>
	                    	</tr>
                    		{/foreach}
							<tr style="border-top:1px black solid;">
	                    		<th>Retail subtotal</th>
	                    		<td>{$results['totalcount']}</td>
	                    		<th align="right">${$presenter->formatPrice($results['total'])}</th>
	                    	</tr>
                    	<tr style="height:40px;"><td colspan="3">&nbsp;</td></tr>
                    </table>
					{/if}
       		  	</div>
            </div>	
            <div class="clear"></div>			
		</div>
		<script type="text/javascript">
		$(function() {
			$("#datepicker input").datepicker();
		});
	
		</script>
<!-- END CLIENT AND SERVICE DETAILS -->

{/block}