{**
 * Main layout for the application
 *
 * @copyright  Copyright (c) 2009 Michal Takacs
 * @package    Salon
 *
 * @param string   $basePath web base path
 * @param array    $flashes  flash messages
 * @param Identity $user     logged user (optional)
 *}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>


<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>@{include #title}</title>
<meta name="ROBOTS" content="NOINDEX,NOFOLLOW"> 
<link href="{$basePath}/css/style-print.css?1.1" rel="stylesheet" type="text/css">
<!--  load libraries -->
<script src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load("jquery", "1.3.2");
google.load("jqueryui", "1.7.2");
</script>
<script src="{$basePath}/js/sms.core.js?1.1"></script>
</head>
<body>
<h1>Bloom Beauty Lounge</h1>
</br />
<p>140 W 19th Street
New York, NY 10011

(212) 255-9355</p>
	
    @{include #content}    

<script type="text/javascript">
//window.print();
//window.close();
</script>

</body>
</html>
