{**
 * Main layout for the application
 *
 * @copyright  Copyright (c) 2009 Michal Takacs
 * @package    Salon
 *
 * @param string   $basePath web base path
 * @param array    $flashes  flash messages
 * @param Identity $user     logged user (optional)
 *}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>


<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Mochi!</title>
<meta name="ROBOTS" content="NOINDEX,NOFOLLOW"> 
<link href="{$basePath}/css/style.css?1.1" rel="stylesheet" type="text/css">
<link href="{$basePath}/css/ext/redmond/jquery-ui-1.7.2.custom.css" rel="stylesheet" type="text/css">
<!--  load libraries -->
<script src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load("jquery", "1.4.2");
</script>
<script src="{$basePath}/js/sms.core.js?1.21"></script>
<script src="{$basePath}/js/ext/jquery-ui-1.7.2.custom.min.js"></script>
</head>
<body>

	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-16511681-1']);
	  _gaq.push(['_setDomainName', '.getmochi.com']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>


<div id="loading" style="z-index:500;display:none;position:absolute;top:0px;left:0px;">
<img src="{$basePath}/images/loading.gif">
</div>
<div class="container">
   
    	<div class="adminBar" style="height:34px;">
        	<div class="busName"><h1><a href="/" title="Go To Home Page">Get <strong>Mochi</strong></a></h1></div>
        	{if isset($user)}
            <div class="adminBtn"><a href="{link Reports:daily}" title="View Reports">Reports</a></div>
            <div class="adminBtn"><a href="javascript:alert('Not implemented. Patience, young Jedi!');" title="Admininstrative Tools">Admin</a></div>            
            <div class="adminBtn"><a href="{link Checkout:search}" title="List All Transactions">Transactions</a></div>
            <div class="adminBtn"><a href="{link Profile:search}" title="List All Clients">Clients</a></div>
            <div class="adminBtn"><a href="{link Calendar:home}" title="Calendary &amp; Booking">Calendar</a></div>
            <div class="adminPrefsTxt">
	            <a href="javascript:alert('Not implemented. Patience, young Jedi!');" title="My Preferences" class="greyLink">My Preferences</a> &nbsp;&nbsp;&nbsp;            
	            <a href="{link logout}" title="Log Out" class="greyLink">Log Out</a>
            </div>           
            <div class="adminName">Hi {$user['name']}!</div>
            <div class="clear"></div>
            {/if}
        </div>
    
    @{include #content} 
</div>   
<script type="text/javascript">
$(document).ready(function() {
	sms.seamless.init();
});
</script>

</body>
</html>