{**
 * Main layout for the application
 *
 * @copyright  Copyright (c) 2009 Michal Takacs
 * @package    Salon
 *
 * @param string   $basePath web base path
 * @param array    $flashes  flash messages
 * @param Identity $user     logged user (optional)
 *}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>


<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Mochi!</title>
<meta name="ROBOTS" content="NOINDEX,NOFOLLOW">
<link href="{$basePath}/css/sms-styles-v2.css?1.1" rel="stylesheet" type="text/css">
<link href="{$basePath}/css/ext/redmond/jquery-ui-1.7.2.custom.css" rel="stylesheet" type="text/css">
<!--  load libraries -->
<script src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load("jquery", "1.4.2", { uncompressed:true });
</script>
<script src="{$basePath}/js/sms.core.js?1.21"></script>
<script src="{$basePath}/js/ext/jquery-ui-1.7.2.custom.min.js"></script>
</head>
<body>
<div id="loading" style="z-index:500;display:none;position:absolute;top:0px;left:0px;">
<img src="{$basePath}/images/loading.gif">
</div>
<div class="container">
   
    	<div class="adminBar">
        	<div class="busName"><p><a href="/" title="Go To Home Page">Get <strong>Mochi</strong></a></p></div>
        	{if isset($user)}
            <div class="adminBtn"><a href="{link Reports:daily}" title="View Reports">Reports</a></div>
            <div class="adminBtn"><a href="javascript:alert('Not implemented. Patience, young Jedi!');" title="Admininstrative Tools">Admin</a></div>            
            <div class="adminBtn"><a href="{link Checkout:search}" title="List All Transactions">Transactions</a></div>
            <div class="adminBtn"><a href="{link Profile:search}" title="List All Clients">Clients</a></div>
            <div class="adminBtn"><a href="{link Calendar:home}" title="Calendary &amp; Booking">Calendar</a></div>
            <div class="adminBtn"><a href="javascript:alert('Not implemented. Patience, young Jedi!');" title="My Preferences" class="greyLink">My Preferences</a></div>
            <div class="adminBtn"><a href="{link logout}" title="Log Out" class="greyLink">Log Out</a></div>                        
            <div class="clear"></div>
            {/if}
        </div>
        

    <!-- START TOP SEARCH AND CHECKOUT -->
    {include "Checkout/find-user.phtml"}
    	<div class="calSearchCheckBar">
        	<div class="calCheckoutBtn floatLeft">
            	<a href="{link Calendar:home}" title="Calendar">
                	<div class="calIconBig floatLeft"></div>
                    <div class="calCheckoutBtnTxt floatLeft">Calendar</div>
                </a>
            </div>

            <div class="searchBox">
            	{widget searchForm begin}
            	{$control['searchForm']['q']->control}
                {widget searchForm end }
                <div class="clear"></div>
            </div>
            <div class="resultBox qs-results" style="display:none;">
            <div id="snippet--results"></div>
            </div>

            <div class="calCheckoutBtn floatLeft">
            	<a href="#" onclick="sms.checkout.show_checkout_step_1(); return false;" title="Checkout">
                	<div class="checkoutIconBig floatLeft"></div>
                    <div class="calCheckoutBtnTxt floatLeft">Checkout</div>
              </a>
            </div>
        </div>


    <!-- END TOP SEARCH AND CHECKOUT -->

    @{include #content} 
</div>
<script type="text/javascript">
$(document).ready(function() {
	sms.seamless.init();
});
</script>

<script type="text/javascript">

$('.searchBox input').attr({'autocomplete':'off'})
	.focus()
	.bind('keydown', { url: {link QuickSearch:quicksearchhome}}, sms.quicksearch.keydown)
	.bind('keyup', { url: {link QuickSearch:quicksearchhome}}, sms.quicksearch.keyup);

sms.quicksearch.url = {link QuickSearch:quicksearchhome};
</script>

<script type="text/javascript">
 var gaq = gaq || []; gaq.push(['setAccount', 'UA-12019250-3']); gaq.push(['trackPageview']);

(function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga); })();
</script>
</body>
</html>